apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-conjur
    kind: SecretStore
  target:
    name: conjur-secret
  data:
  - secretKey: username
    remoteRef:
      key: data/vault/rh_bot/rh_bot_vault_creds/username
