#!/bin/bash 
set -eo pipefail

source ../config/conjur.config
source ../config/utils.sh

# Starts an CONJUR Master HA cluster

main() {
  ./precheck_master.sh
  ./stp_cluster
  master_network_up
  shared_volumes_up
  master_up
  start_standbys
  haproxy_up
  cli_up
  ./enable_dap_node_for_authnk8s.sh
  ./enable_dap_node_for_authnjwt_for_k8s.sh
  cluster_up
  configure_standbys
  follower_up
  wait_till_master_is_responsive
  load_demo_policy
  announce "The Conjur master endpoint is at: $CONJUR_LEADER_HOSTNAME:$CONJUR_LEADER_PORT"
  echo
}

############################
master_network_up() {
  $DOCKER network create $CONJUR_NETWORK
}

############################
shared_volumes_up() {
  $DOCKER volume create $CONJUR_AUDIT_VOLUME
  $DOCKER volume create $CONJUR_NGINX_VOLUME
}

############################
master_up() {
  echo "-----"
  announce "Initializing Conjur Master"
  $DOCKER run -d \
    --name $CONJUR_LEADER_CONTAINER_NAME		\
    --label role=conjur_node				\
    --volume $CONJUR_AUDIT_VOLUME:/var/log/conjur 	\
    --volume $CONJUR_NGINX_VOLUME:/var/log/nginx 	\
    --restart unless-stopped 				\
    --security-opt $SECURITY_OPT 			\
    $CONJUR_APPLIANCE_IMAGE

  $DOCKER network connect $CONJUR_NETWORK $CONJUR_LEADER_CONTAINER_NAME

  $DOCKER exec -it $CONJUR_LEADER_CONTAINER_NAME	\
    evoke configure master				\
    -h $CONJUR_LEADER_HOSTNAME				\
    -p $CONJUR_ADMIN_PASSWORD				\
    --master-altnames "$LEADER_ALTNAMES"		\
    --follower-altnames "$FOLLOWER_ALTNAMES"		\
    --accept-eula		    			\
    $CONJUR_ACCOUNT

  echo "Caching Certificate from Conjur in ../etc..."
  mkdir -p $CACHE_DIR
  rm -f $LEADER_CERT_FILE
					# cache cert for copying to other containers
  $DOCKER cp -L $CONJUR_LEADER_CONTAINER_NAME:/opt/conjur/etc/ssl/conjur.pem $LEADER_CERT_FILE

  echo "Caching Conjur Follower seed files in ../etc..."
  $DOCKER exec $CONJUR_LEADER_CONTAINER_NAME evoke seed follower conjur-follower > $FOLLOWER_SEED_FILE
}

############################
start_standbys() {

  announce "Initializing Standbys"

  start_standby $CONJUR_STANDBY1_NAME
  start_standby $CONJUR_STANDBY2_NAME
}

############################
start_standby() {
  local standby_name=$1; shift

  echo "-----"
  announce "Starting Conjur Standby $standby_name"
  $DOCKER run -d \
    --name $standby_name \
    --label role=conjur_node \
    --restart always \
    --security-opt seccomp:unconfined \
    $CONJUR_APPLIANCE_IMAGE

  $DOCKER network connect $CONJUR_NETWORK $standby_name
}

############################
configure_standbys() {
  echo "Preparing standby seed files..."

  mkdir -p tmp
  master_ip=$($DOCKER inspect $CONJUR_LEADER_CONTAINER_NAME --format "{{ .NetworkSettings.IPAddress }}")

  $DOCKER exec $CONJUR_LEADER_CONTAINER_NAME evoke seed standby $CONJUR_STANDBY1_NAME $CONJUR_LEADER_CONTAINER_NAME > ./tmp/${CONJUR_STANDBY1_NAME}-seed.tar
  configure_standby $CONJUR_STANDBY1_NAME $master_ip

  $DOCKER exec $CONJUR_LEADER_CONTAINER_NAME evoke seed standby $CONJUR_STANDBY2_NAME $CONJUR_LEADER_CONTAINER_NAME > ./tmp/${CONJUR_STANDBY2_NAME}-seed.tar
  configure_standby $CONJUR_STANDBY2_NAME $master_ip

#  rm -rf tmp

  echo "Starting synchronous replication..."

  $DOCKER exec $CONJUR_LEADER_CONTAINER_NAME evoke replication sync start

  echo "Standbys configured."
}  

############################
configure_standby() {
  local standby_name=$1; shift
  local master_ip=$1; shift

  printf "Configuring standby %s...\n" $standby_name

  $DOCKER cp ./tmp/${standby_name}-seed.tar $standby_name:/tmp/${standby_name}-seed.tar
    
  $DOCKER exec $standby_name \
	evoke unpack seed /tmp/${standby_name}-seed.tar
  $DOCKER exec $standby_name \
	evoke configure standby -a $master_ip -p $CONJUR_LEADER_PORT

  # enroll standby node in etcd cluster
  $DOCKER exec -it $standby_name \
	evoke cluster enroll -n $standby_name conjur-cluster
}

############################
haproxy_up() {
  $DOCKER run -d \
    --name $HAPROXY_CONTAINER_NAME \
    --label role=haproxy \
    -p "$CONJUR_LEADER_PORT:443" \
    -p "$CONJUR_LEADER_PGSYNC_PORT:5432" \
    -p "$CONJUR_LEADER_PGAUDIT_PORT:1999" \
    --privileged \
    --restart always \
    --entrypoint "/start.sh" \
    $HAPROXY_IMAGE

  $DOCKER network connect $CONJUR_NETWORK $HAPROXY_CONTAINER_NAME

  $DOCKER restart $HAPROXY_CONTAINER_NAME
}

############################
cli_up() {

  announce "Creating CLI container."

  $DOCKER run -d \
    --name $CLI_CONTAINER_NAME \
    --label role=cli \
    --restart always \
    --add-host "$CONJUR_LEADER_HOSTNAME:$CONJUR_LEADER_HOST_IP" \
    --security-opt seccomp:unconfined \
    --entrypoint sh \
    $CLI_IMAGE \
    -c "sleep infinity" 

  wait_till_master_is_responsive

  # Initialize connection to service (create .conjurrc and conjur-xx.pem cert)
  $DOCKER exec -it $CLI_CONTAINER_NAME \
	bash -c "echo yes | conjur init -a $CONJUR_ACCOUNT -u $CONJUR_APPLIANCE_URL --force=true"
  $DOCKER exec $CLI_CONTAINER_NAME \
	conjur authn login -u admin -p $CONJUR_ADMIN_PASSWORD
  $DOCKER exec $CLI_CONTAINER_NAME \
	mkdir /policy

  echo "CLI container configured."
}

############################
cluster_up() {
  announce "Initializing etcd cluster..."

  wait_till_master_is_responsive
  $DOCKER cp ./policy/cluster-policy.yml conjur-cli:/policy/cluster-policy.yml
  $DOCKER exec -it conjur-cli conjur policy load root ./policy/cluster-policy.yml
  $DOCKER exec -it $CONJUR_LEADER_CONTAINER_NAME evoke cluster enroll -n $CONJUR_LEADER_CONTAINER_NAME conjur-cluster

 echo "Cluster initialized."
}

############################
wait_till_master_is_responsive() {
  set +e
  master_is_healthy=""
  while [[ "$master_is_healthy" == "" ]]; do
    sleep 2
    master_is_healthy=$($DOCKER exec -it conjur-cli curl -k $CONJUR_APPLIANCE_URL/health | grep "ok" | tail -1 | grep "true")
  done
  set -e
}

############################
follower_up() {
  # Bring up Conjur Follower node
  $DOCKER run -d \
    --name $CONJUR_FOLLOWER_CONTAINER_NAME \
    --label role=conjur_node \
    -p "$CONJUR_FOLLOWER_PORT:443" \
    --add-host "$CONJUR_LEADER_HOSTNAME:$CONJUR_LEADER_HOST_IP" \
    --restart always \
    --security-opt seccomp:unconfined \
    $CONJUR_APPLIANCE_IMAGE

  echo "Initializing Conjur Follower"
  $DOCKER cp $FOLLOWER_SEED_FILE \
		$CONJUR_FOLLOWER_CONTAINER_NAME:/tmp/follower-seed.tar
  $DOCKER exec $CONJUR_FOLLOWER_CONTAINER_NAME \
		evoke unpack seed /tmp/follower-seed.tar
  $DOCKER exec $CONJUR_FOLLOWER_CONTAINER_NAME \
		evoke configure follower -p $CONJUR_LEADER_PORT

  echo "Caching CONJUR Follower cert ..."
  rm -f $FOLLOWER_CERT_FILE
  $DOCKER cp -L $CONJUR_FOLLOWER_CONTAINER_NAME:/opt/conjur/etc/ssl/conjur-follower.pem $FOLLOWER_CERT_FILE

  echo "Follower configured."
}

############################
load_demo_policy() {
  # Laod policy & init variables
  load_policy_REST.sh root ./policy/demo-policy.yml
  var_value_add_REST.sh secrets/db-username "This-is-the-DB-username"
  var_value_add_REST.sh secrets/db-password $(openssl rand -hex 12)
}

main $@
