#!/bin/bash

if [[ "$(docker ps | grep mssqlserver)" == "" ]]; then
  exit 0
fi

echo
read -p "Remove running database containers? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit -1
fi

echo "Stopping and removing mssqlserver & mssql-cli containers..."
docker stop mssqlserver > /dev/null && docker rm mssqlserver > /dev/null
docker stop mssql-cli > /dev/null && docker rm mssql-cli > /dev/null
