---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DBName:   bXlhcHBEQg==
stringData:
  conjur-map: |-
    username:  {{ .Values.app_safe_secret_id_01 }} 
    password:  {{ .Values.app_safe_secret_id_02 }} 
