apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dk-cfg-example
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-conjur
    kind: SecretStore
  data:
  - secretKey: mysecret
    remoteRef:
      key: {{ .Values.app_safe_secret_id_01 }}
  target:
    name: docker-config
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .mysecret | toString }}"
    name: secret-to-be-created
    creationPolicy: Owner
