---
# Define namespace user
apiVersion: user.openshift.io/v1
kind: User
metadata:
  name: {{ APP_NAMESPACE_NAME }}
fullName: CyberArk Lab {{ APP_NAMESPACE_NAME }}
identities:
  - 'cluster_admin_htpasswd_provider:{{ APP_NAMESPACE_NAME }}'

---
# Define project namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ APP_NAMESPACE_NAME }}
  labels:
    name: {{ APP_NAMESPACE_NAME }}

---
# Grant the authentication service access to pods in {{ APP_NAMESPACE_NAME }} namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-authn-service
  namespace: {{ APP_NAMESPACE_NAME }}
subjects:
- kind: ServiceAccount
  name: conjur-authn-service
  namespace: {{ CYBERARK_NAMESPACE_NAME }}
roleRef:
  kind: ClusterRole
  name: conjur-authn-role
  apiGroup: rbac.authorization.k8s.io

---
# Grant {{ APP_NAMESPACE_ADMIN }} namespace admin privileges
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
  namespace: {{ APP_NAMESPACE_NAME }}
subjects:
- kind: User
  name: {{ APP_NAMESPACE_ADMIN }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
