---
# Create CyberArk namespace for Followers
apiVersion: v1
kind: Namespace
metadata:
  name: {{ CYBERARK_NAMESPACE_NAME }}
  labels:
    name: {{ CYBERARK_NAMESPACE_NAME }}

---
# Create service account for authentication service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur-follower
  namespace: {{ CYBERARK_NAMESPACE_NAME }}

---
# Create cluster role for authentication service access to pods
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conjur-authn-role
rules:
- apiGroups: [""]
  resources: ["pods", "serviceaccounts"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: [ "deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: [ "deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]

---
# Grant the Follower service account access to pods in CyberArk namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-follower-access-grant
  namespace: {{ CYBERARK_NAMESPACE_NAME }}
subjects:
- kind: ServiceAccount
  name: conjur-follower
  namespace: {{ CYBERARK_NAMESPACE_NAME }}
roleRef:
  kind: ClusterRole
  name: conjur-authn-role
  apiGroup: rbac.authorization.k8s.io

---
# Cluster role to enable other projects to access and copy the DAP config map
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conjur-cm-access-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["conjur-config"]
  verbs: ["get", "list"]

---
# Grant namespace admin role to user {{ CYBERARK_NAMESPACE_ADMIN }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-admin-access-binding
  namespace: {{ CYBERARK_NAMESPACE_NAME }}
subjects:
- kind: User
  name: {{ CYBERARK_NAMESPACE_ADMIN }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
# Grant cluster admin access to the JWKS issuer discovery API
# see https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oidc-reviewer
roleRef:
  kind: ClusterRole
  name: system:service-account-issuer-discovery
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:unauthenticated
