---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  labels:
    app: petstore
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: petstore
  type: LoadBalancer

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: petstore
  name: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      serviceAccountName: app-example-secretless

      containers:
      - image: {{ APP_IMAGE }}
        imagePullPolicy: IfNotPresent
        name: petstore
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pets
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5

        env:
          - name: DB_PLATFORM
#            value: "mssql"
            value: "postgresql"
          - name: DB_URL
#            value: "sqlserver://localhost;databaseName=test_app"
            value: "postgresql://localhost/test_app?sslmode=disable"
          - name: DB_USERNAME
            value: ignore
          - name: DB_PASSWORD
            value: ignore

      - image: {{ SECRETLESS_BROKER_IMAGE }}
        imagePullPolicy: IfNotPresent
        name: secretless
        # args refer to values mounted from config map, populated from Conjur
        args: ["-f", "/etc/secretless/secretless.yml"]
        env:

        # values from pod metadata
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

        # values from DAP config map
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: CONJUR_VERSION
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: CONJUR_ACCOUNT
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: CONJUR_APPLIANCE_URL
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: CONJUR_SSL_CERTIFICATE

        # values from app config map
          - name: CONJUR_AUTHN_URL
            valueFrom:
              configMapKeyRef:
                name: "{{ APP_CONFIG_MAP }}"
                key: conjur-authn-url
          - name: CONJUR_AUTHN_LOGIN
            valueFrom:
              configMapKeyRef:
                name: "{{ APP_CONFIG_MAP }}"
                key: conjur-authn-login

        volumeMounts:
        - name: config
          mountPath: "/etc/secretless"
          readOnly: true

      volumes:
      - name: config
        configMap:
          name: secretless-config
