---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # base64-encoded "myappDB"
  DBName:   bXlhcHBEQg==
stringData:
  conjur-map: |-   
    username: DemoVault/CICD/CICD_Secrets/Database-Oracle-OracleDBuser/username
    password: DemoVault/CICD/CICD_Secrets/Database-Oracle-OracleDBuser/password
