# Grants the default service account a rolebinding
# to a clusterrole for secrets access & patching.
# Apps run as the default service account unless
# otherwise specified. Similarly, the application 
# identity in DAP assumes the default SA unless 
# otherwise specified.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ APP_NAMESPACE_NAME }}
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: {{ APP_NAMESPACE_NAME }}
    name: default
roleRef:
  kind: ClusterRole
  name: secrets-access
  apiGroup: rbac.authorization.k8s.io
