#!/bin/bash

source ../../../config/conjur.config
source ../../../bin/conjur_utils.sh

if [[ "$PLATFORM" == "openshift" ]]; then
  uname=$($CLI whoami 2> /dev/null)
  if [[ "$uname" != "user"* ]]; then
    echo "Please login as a lab user first."
    exit -1
  fi
else
  uname=$APP_NAMESPACE_NAME
fi

main() {
  CMD=$1
  case $CMD in
    y*)
        create_yaml_files
        ;;
    a*)
        deploy_app
        ;;
    e*)
        $CLI exec -it $($CLI get pods -n $APP_NAMESPACE_NAME | grep app-example-init | grep Running | awk '{print $1}') -n $APP_NAMESPACE_NAME -- bash 
        ;;
    d*)
        reset_lab
        ;;
    c*)
        reset_lab
        rm -f *.yaml
        ;;
    *)
        echo "Usage: $0 [ yaml | apply | exec | delete | clean ]"
        exit -1
  esac
  exit 0
}

########################
create_yaml_files() {
  echo "creating YAML files."

  sed -e "s#{{ APP_NAMESPACE_NAME }}#$uname#g"			\
	./templates/app-init-policy.template.yaml		\
  | sed -e "s#{{ CLUSTER_AUTHN_ID }}#$CLUSTER_AUTHN_ID#g"	\
  | sed -e "s#{{ SECRETS_ACCESS_ROLE }}#$SECRETS_ACCESS_ROLE#g"	\
  > ./app-init-policy.yaml

  $CLI get cm conjur-config -n $CYBERARK_NAMESPACE_NAME -o yaml				\
    | sed "s/namespace: $CYBERARK_NAMESPACE_NAME/namespace: $APP_NAMESPACE_NAME/"	\
    > ./conjur-config-cm.yaml

  sed -e "s#{{ APP_IMAGE }}#$APP_IMAGE#g"				\
	./templates/app-init-manifest.template.yaml			\
  | sed -e "s#{{ AUTHENTICATOR_IMAGE }}#$AUTHENTICATOR_IMAGE#g"		\
  | sed -e "s#{{ APP_NAMESPACE_NAME }}#$APP_NAMESPACE_NAME#g"		\
  | sed -e "s#{{ CONJUR_AUTHN_URL }}#$CONJUR_AUTHN_URL#g"		\
  | sed -e "s#{{ DB_URL }}#$DB_URL#g"					\
  > ./app-init-manifest.yaml
}

########################
# apply manifests to deploy app
deploy_app() {
  conjur_append_policy $APP_NAMESPACE_NAME ./app-init-policy.yaml
  if [[ "$($CLI get cm conjur-config -n $APP_NAMESPACE_NAME --ignore-not-found)" == "" ]]; then
    $CLI apply -f ./conjur-config-cm.yaml -n $APP_NAMESPACE_NAME
  fi
  $CLI apply -f ./app-init-manifest.yaml -n $APP_NAMESPACE_NAME
}

########################
# delete existing deployments, cm, etc.
reset_lab() {
  $CLI delete -f ./app-init-manifest.yaml -n $APP_NAMESPACE_NAME --ignore-not-found
}

main "$@"
