apiVersion: v1
data:
  CLUSTER_AUTHN_ID: mac-k8s
  CONJUR_ACCOUNT: dev
  CONJUR_APPLIANCE_URL: https://conjur-follower.cyberark.svc.cluster.local
  CONJUR_AUTHN_TOKEN_FILE: /run/conjur/access-token
  CONJUR_AUTHN_URL: https://conjur-follower.cyberark.svc.cluster.local/api/authn-k8s/mac-k8s
  CONJUR_FOLLOWER_CERTIFICATE: |
    -----BEGIN CERTIFICATE-----
    MIIDfzCCAmegAwIBAgIVANHyW55gZOxz/4IDbIkpLxvqrq5hMA0GCSqGSIb3DQEB
    CwUAMEMxDDAKBgNVBAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMR8wHQYDVQQD
    DBZjb25qdXItbWFzdGVyLW1pbmlrdWJlMB4XDTIyMTEwMjIwMDkzNloXDTMyMTAz
    MDIwMDkzNlowGjEYMBYGA1UEAwwPY29uanVyLWZvbGxvd2VyMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwyGDSfSz9MGdbhtvrjpqC1fz57XsNZcf29FL
    xXG9ypfzWKDAtb5b+w8q/7Qkp2h8IcY0UibyrhdZQM6Zra7j5gOD6y76qHB8F70n
    zh1YcXVkRLJtCRGVy5eRoCT6jgjpRPaK4x4bI1orZPLYDH4jxa0jYSpU6P5QUUQw
    MSlDcODRDLvzSQdbhe9ajdvemOHZs6wS1PB705I6D4eFTjYmrEBnNlztXpRc0oPb
    upZvcyofvRQJ0Vrw6zQILWGgAs9qwII/hJgVWy7yaP8dLIuX1Q4aLpiyF7nseaSs
    PuCVhYkmzZUK4RqN+Mkk7WSzGGSBmj1Cyr3cLnPseJYKgsg2FwIDAQABo4GSMIGP
    MA4GA1UdDwEB/wQEAwIFoDAdBgNVHQ4EFgQU2jmj7l5rSw0yVb/vlWAYkK/YBwkw
    XgYDVR0RBFcwVYIPY29uanVyLWZvbGxvd2Vygipjb25qdXItZm9sbG93ZXIuY3li
    ZXJhcmsuc3ZjLmNsdXN0ZXIubG9jYWyCFmNvbmp1ci1tYXN0ZXItbWluaWt1YmUw
    DQYJKoZIhvcNAQELBQADggEBADwTRSp3a8AcNfCmoeG2X2puv8eeUfLHoQX3cgXv
    pxDulN7T1Nu/EbQmjg1dLrSau06R1lEV6T44gH+x9PrXPd093Ksx4zGzFyuHsUf7
    Gx8T5UtVDh55GL/EyO/k/9crVZKkz6ESJKLyHr1tX8EBWG8BT4dkpj1cnukDsFb+
    WTgKLKYskK7u93SSK8ggZ0IfX6uAT8RBy1Us2LUmUQUG2lTkURzSk0Je3EGOorB0
    Ez67wctuNCETJF9NUQLs4PeLYS7gk/SWPbwwIvOUySiYTYb3cqAcbxmkhuoy8nsP
    2PAYzqJ/JEwz9KJyVWBJ2gekgNXMdfTHYswf3SFoLXL/FJg=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDsjCCApqgAwIBAgIJAJ/9iknV65pGMA0GCSqGSIb3DQEBCwUAMEMxDDAKBgNV
    BAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMR8wHQYDVQQDDBZjb25qdXItbWFz
    dGVyLW1pbmlrdWJlMB4XDTIyMTEwMjE4NTE0OVoXDTMyMTAzMDE4NTE0OVowQzEM
    MAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMMFmNvbmp1
    ci1tYXN0ZXItbWluaWt1YmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDd2/bqOsUwDLH5YfRmU0gHllUjX/LMcuseqsfdJ2XWifPEIXLhmAzcbhIR1BWq
    cncdDeC2GaWLHu9onoLdVq8iu/Pnj8wPVI42J1RR5gALAAs8iY2HxijiV0jL8laM
    ibBn2hyUXNyGHlR633Z/BSW5LCw9Fqfw7i9RBRMC7qd749aZ3rnFq3Uv4mgIemjU
    9k4oLSecKBl/xo7dB9gOll1p7PXr1UECy4x+q0O9vm/lXnYNdtQmIialI/C6BWZL
    mtrhDphBgALRw8BjYbBng/sViKA2IrBGPErVlmlJzU1fz2MYmFtjqxfEOlqIWGsn
    MzAttBePP7rjlka1cV7+SH6BAgMBAAGjgagwgaUwSAYDVR0RBEEwP4IWY29uanVy
    LW1hc3Rlci1taW5pa3ViZYIWY29uanVyLW1hc3Rlci1taW5pa3ViZYINY29uanVy
    LW1hc3RlcjAdBgNVHQ4EFgQUUiThEDs33VZit3W/7nd67fGnkeowHwYDVR0jBBgw
    FoAUUiThEDs33VZit3W/7nd67fGnkeowDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMC
    AeYwDQYJKoZIhvcNAQELBQADggEBAArE1s2AbFISLfi4JzBK8u8xqyHSMk041Jgl
    Wwr0Vmt2JEkgpWWuCVKrrX1B4PGc+iclPf1skyWO3IVxYaaj/5v9sdFhPq/ThvaL
    SNBlvkqAIkqfjc0Dhwoj/P2svmxPWHidCrrjQ+qzIyod+iba9KA6Ah48UI6hxPtk
    MYDC50h9bEkYXenMkM0gN8WBeiCBFN3rVpuOiO8g5mozUJ5kAj4BTJ+l/w6keWvd
    NLvXf+TBUgYE2pTSvektBW8DyWV6oFI1e6qaj1mmZoauCUy9Teg1Jb2JZUsf9Eb3
    zxadAvu7I70r5KvzsvnpILYbNpNbFOmgLBkcgLKdxTeo/faIOLE=
    -----END CERTIFICATE-----
  CONJUR_LEADER_CERTIFICATE: |
    -----BEGIN CERTIFICATE-----
    MIIDbTCCAlWgAwIBAgIUR6p6mcxGww9AFdhfqNpz8uHhrEgwDQYJKoZIhvcNAQEL
    BQAwQzEMMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMM
    FmNvbmp1ci1tYXN0ZXItbWluaWt1YmUwHhcNMjIxMTAyMTg1MTUzWhcNMzIxMDMw
    MTg1MTUzWjAhMR8wHQYDVQQDDBZjb25qdXItbWFzdGVyLW1pbmlrdWJlMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5e9gHGWHVsqjkB0ynF52aP6I0mZZ
    LZ1fQsdqqBGuK1h7cZLt0Jb80CYQn1bd1SOv0QRgZQfQygVuqqPnkatyouSLk7XB
    eadjpUT4hrRKJzgVkW5qaecZdq9Rx0R//7QESAys3V9aGds1In4dkhVRHVI+dNJK
    JCiJ7KJPTcARnMsuOS6GwyVBT8NnymwToEFnTt1K0Lz0QOCO0TS9MeRqQmQfbRQJ
    MnzsbGE9uqnZkhUZiUvnSOCzDvKCk+CIgdR1vB76YdmqL+Zv/GDQybfr95H1Nfxe
    W9gJ5g0IrOXMY8gyT7a+DZgaolnILM9bfRGHih9fVt0lH/4dc1gCOF2kzQIDAQAB
    o3sweTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0OBBYEFNo5o+5ea0sNMlW/75VgGJCv
    2AcJMEgGA1UdEQRBMD+CFmNvbmp1ci1tYXN0ZXItbWluaWt1YmWCFmNvbmp1ci1t
    YXN0ZXItbWluaWt1YmWCDWNvbmp1ci1tYXN0ZXIwDQYJKoZIhvcNAQELBQADggEB
    ACWVjhCJV9CW2ABtFnvJizoxd3d7QqgVCTBcHlM8jzjuiBTqa++rlgUW732A9EmM
    YfWePsIALbS3elbU2ewepjCJS5WsX/W9zL46rw9Cs7PYr8g69yDJUo+MHjDXBDik
    DQv5155OI3FjgPR5FXvsxv/tN4P7y/V0nomgOHZdhoFBHSp9ehzW7AHUPUF7m0Tt
    5Nb633j9DIwBCZS64271aoeX/zffYds7PZT29lXcUVRnITCMojE97Cv0g+6Yy/sm
    D0fBZwJevuPqmBsWuysn0O0xNiO5ymkR9ugIJZNQNygyLuI9AievzzvZZXfvS8Jr
    jAz1A8koFUY2RruNsmyiYA8=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDsjCCApqgAwIBAgIJAJ/9iknV65pGMA0GCSqGSIb3DQEBCwUAMEMxDDAKBgNV
    BAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMR8wHQYDVQQDDBZjb25qdXItbWFz
    dGVyLW1pbmlrdWJlMB4XDTIyMTEwMjE4NTE0OVoXDTMyMTAzMDE4NTE0OVowQzEM
    MAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMMFmNvbmp1
    ci1tYXN0ZXItbWluaWt1YmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDd2/bqOsUwDLH5YfRmU0gHllUjX/LMcuseqsfdJ2XWifPEIXLhmAzcbhIR1BWq
    cncdDeC2GaWLHu9onoLdVq8iu/Pnj8wPVI42J1RR5gALAAs8iY2HxijiV0jL8laM
    ibBn2hyUXNyGHlR633Z/BSW5LCw9Fqfw7i9RBRMC7qd749aZ3rnFq3Uv4mgIemjU
    9k4oLSecKBl/xo7dB9gOll1p7PXr1UECy4x+q0O9vm/lXnYNdtQmIialI/C6BWZL
    mtrhDphBgALRw8BjYbBng/sViKA2IrBGPErVlmlJzU1fz2MYmFtjqxfEOlqIWGsn
    MzAttBePP7rjlka1cV7+SH6BAgMBAAGjgagwgaUwSAYDVR0RBEEwP4IWY29uanVy
    LW1hc3Rlci1taW5pa3ViZYIWY29uanVyLW1hc3Rlci1taW5pa3ViZYINY29uanVy
    LW1hc3RlcjAdBgNVHQ4EFgQUUiThEDs33VZit3W/7nd67fGnkeowHwYDVR0jBBgw
    FoAUUiThEDs33VZit3W/7nd67fGnkeowDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMC
    AeYwDQYJKoZIhvcNAQELBQADggEBAArE1s2AbFISLfi4JzBK8u8xqyHSMk041Jgl
    Wwr0Vmt2JEkgpWWuCVKrrX1B4PGc+iclPf1skyWO3IVxYaaj/5v9sdFhPq/ThvaL
    SNBlvkqAIkqfjc0Dhwoj/P2svmxPWHidCrrjQ+qzIyod+iba9KA6Ah48UI6hxPtk
    MYDC50h9bEkYXenMkM0gN8WBeiCBFN3rVpuOiO8g5mozUJ5kAj4BTJ+l/w6keWvd
    NLvXf+TBUgYE2pTSvektBW8DyWV6oFI1e6qaj1mmZoauCUy9Teg1Jb2JZUsf9Eb3
    zxadAvu7I70r5KvzsvnpILYbNpNbFOmgLBkcgLKdxTeo/faIOLE=
    -----END CERTIFICATE-----
  CONJUR_LEADER_HOSTNAME: conjur-master-minikube
  CONJUR_LEADER_PORT: "443"
  CONJUR_LEADER_URL: https://conjur-master-minikube:443
  CONJUR_VERSION: "5"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"CLUSTER_AUTHN_ID":"mac-k8s","CONJUR_ACCOUNT":"dev","CONJUR_APPLIANCE_URL":"https://conjur-follower.cyberark.svc.cluster.local","CONJUR_AUTHN_TOKEN_FILE":"/run/conjur/access-token","CONJUR_AUTHN_URL":"https://conjur-follower.cyberark.svc.cluster.local/api/authn-k8s/mac-k8s","CONJUR_FOLLOWER_CERTIFICATE":"-----BEGIN CERTIFICATE-----\nMIIDfzCCAmegAwIBAgIVANHyW55gZOxz/4IDbIkpLxvqrq5hMA0GCSqGSIb3DQEB\nCwUAMEMxDDAKBgNVBAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMR8wHQYDVQQD\nDBZjb25qdXItbWFzdGVyLW1pbmlrdWJlMB4XDTIyMTEwMjIwMDkzNloXDTMyMTAz\nMDIwMDkzNlowGjEYMBYGA1UEAwwPY29uanVyLWZvbGxvd2VyMIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwyGDSfSz9MGdbhtvrjpqC1fz57XsNZcf29FL\nxXG9ypfzWKDAtb5b+w8q/7Qkp2h8IcY0UibyrhdZQM6Zra7j5gOD6y76qHB8F70n\nzh1YcXVkRLJtCRGVy5eRoCT6jgjpRPaK4x4bI1orZPLYDH4jxa0jYSpU6P5QUUQw\nMSlDcODRDLvzSQdbhe9ajdvemOHZs6wS1PB705I6D4eFTjYmrEBnNlztXpRc0oPb\nupZvcyofvRQJ0Vrw6zQILWGgAs9qwII/hJgVWy7yaP8dLIuX1Q4aLpiyF7nseaSs\nPuCVhYkmzZUK4RqN+Mkk7WSzGGSBmj1Cyr3cLnPseJYKgsg2FwIDAQABo4GSMIGP\nMA4GA1UdDwEB/wQEAwIFoDAdBgNVHQ4EFgQU2jmj7l5rSw0yVb/vlWAYkK/YBwkw\nXgYDVR0RBFcwVYIPY29uanVyLWZvbGxvd2Vygipjb25qdXItZm9sbG93ZXIuY3li\nZXJhcmsuc3ZjLmNsdXN0ZXIubG9jYWyCFmNvbmp1ci1tYXN0ZXItbWluaWt1YmUw\nDQYJKoZIhvcNAQELBQADggEBADwTRSp3a8AcNfCmoeG2X2puv8eeUfLHoQX3cgXv\npxDulN7T1Nu/EbQmjg1dLrSau06R1lEV6T44gH+x9PrXPd093Ksx4zGzFyuHsUf7\nGx8T5UtVDh55GL/EyO/k/9crVZKkz6ESJKLyHr1tX8EBWG8BT4dkpj1cnukDsFb+\nWTgKLKYskK7u93SSK8ggZ0IfX6uAT8RBy1Us2LUmUQUG2lTkURzSk0Je3EGOorB0\nEz67wctuNCETJF9NUQLs4PeLYS7gk/SWPbwwIvOUySiYTYb3cqAcbxmkhuoy8nsP\n2PAYzqJ/JEwz9KJyVWBJ2gekgNXMdfTHYswf3SFoLXL/FJg=\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIDsjCCApqgAwIBAgIJAJ/9iknV65pGMA0GCSqGSIb3DQEBCwUAMEMxDDAKBgNV\nBAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMR8wHQYDVQQDDBZjb25qdXItbWFz\ndGVyLW1pbmlrdWJlMB4XDTIyMTEwMjE4NTE0OVoXDTMyMTAzMDE4NTE0OVowQzEM\nMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMMFmNvbmp1\nci1tYXN0ZXItbWluaWt1YmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB\nAQDd2/bqOsUwDLH5YfRmU0gHllUjX/LMcuseqsfdJ2XWifPEIXLhmAzcbhIR1BWq\ncncdDeC2GaWLHu9onoLdVq8iu/Pnj8wPVI42J1RR5gALAAs8iY2HxijiV0jL8laM\nibBn2hyUXNyGHlR633Z/BSW5LCw9Fqfw7i9RBRMC7qd749aZ3rnFq3Uv4mgIemjU\n9k4oLSecKBl/xo7dB9gOll1p7PXr1UECy4x+q0O9vm/lXnYNdtQmIialI/C6BWZL\nmtrhDphBgALRw8BjYbBng/sViKA2IrBGPErVlmlJzU1fz2MYmFtjqxfEOlqIWGsn\nMzAttBePP7rjlka1cV7+SH6BAgMBAAGjgagwgaUwSAYDVR0RBEEwP4IWY29uanVy\nLW1hc3Rlci1taW5pa3ViZYIWY29uanVyLW1hc3Rlci1taW5pa3ViZYINY29uanVy\nLW1hc3RlcjAdBgNVHQ4EFgQUUiThEDs33VZit3W/7nd67fGnkeowHwYDVR0jBBgw\nFoAUUiThEDs33VZit3W/7nd67fGnkeowDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMC\nAeYwDQYJKoZIhvcNAQELBQADggEBAArE1s2AbFISLfi4JzBK8u8xqyHSMk041Jgl\nWwr0Vmt2JEkgpWWuCVKrrX1B4PGc+iclPf1skyWO3IVxYaaj/5v9sdFhPq/ThvaL\nSNBlvkqAIkqfjc0Dhwoj/P2svmxPWHidCrrjQ+qzIyod+iba9KA6Ah48UI6hxPtk\nMYDC50h9bEkYXenMkM0gN8WBeiCBFN3rVpuOiO8g5mozUJ5kAj4BTJ+l/w6keWvd\nNLvXf+TBUgYE2pTSvektBW8DyWV6oFI1e6qaj1mmZoauCUy9Teg1Jb2JZUsf9Eb3\nzxadAvu7I70r5KvzsvnpILYbNpNbFOmgLBkcgLKdxTeo/faIOLE=\n-----END CERTIFICATE-----\n","CONJUR_LEADER_CERTIFICATE":"-----BEGIN CERTIFICATE-----\nMIIDbTCCAlWgAwIBAgIUR6p6mcxGww9AFdhfqNpz8uHhrEgwDQYJKoZIhvcNAQEL\nBQAwQzEMMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMM\nFmNvbmp1ci1tYXN0ZXItbWluaWt1YmUwHhcNMjIxMTAyMTg1MTUzWhcNMzIxMDMw\nMTg1MTUzWjAhMR8wHQYDVQQDDBZjb25qdXItbWFzdGVyLW1pbmlrdWJlMIIBIjAN\nBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5e9gHGWHVsqjkB0ynF52aP6I0mZZ\nLZ1fQsdqqBGuK1h7cZLt0Jb80CYQn1bd1SOv0QRgZQfQygVuqqPnkatyouSLk7XB\neadjpUT4hrRKJzgVkW5qaecZdq9Rx0R//7QESAys3V9aGds1In4dkhVRHVI+dNJK\nJCiJ7KJPTcARnMsuOS6GwyVBT8NnymwToEFnTt1K0Lz0QOCO0TS9MeRqQmQfbRQJ\nMnzsbGE9uqnZkhUZiUvnSOCzDvKCk+CIgdR1vB76YdmqL+Zv/GDQybfr95H1Nfxe\nW9gJ5g0IrOXMY8gyT7a+DZgaolnILM9bfRGHih9fVt0lH/4dc1gCOF2kzQIDAQAB\no3sweTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0OBBYEFNo5o+5ea0sNMlW/75VgGJCv\n2AcJMEgGA1UdEQRBMD+CFmNvbmp1ci1tYXN0ZXItbWluaWt1YmWCFmNvbmp1ci1t\nYXN0ZXItbWluaWt1YmWCDWNvbmp1ci1tYXN0ZXIwDQYJKoZIhvcNAQELBQADggEB\nACWVjhCJV9CW2ABtFnvJizoxd3d7QqgVCTBcHlM8jzjuiBTqa++rlgUW732A9EmM\nYfWePsIALbS3elbU2ewepjCJS5WsX/W9zL46rw9Cs7PYr8g69yDJUo+MHjDXBDik\nDQv5155OI3FjgPR5FXvsxv/tN4P7y/V0nomgOHZdhoFBHSp9ehzW7AHUPUF7m0Tt\n5Nb633j9DIwBCZS64271aoeX/zffYds7PZT29lXcUVRnITCMojE97Cv0g+6Yy/sm\nD0fBZwJevuPqmBsWuysn0O0xNiO5ymkR9ugIJZNQNygyLuI9AievzzvZZXfvS8Jr\njAz1A8koFUY2RruNsmyiYA8=\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIDsjCCApqgAwIBAgIJAJ/9iknV65pGMA0GCSqGSIb3DQEBCwUAMEMxDDAKBgNV\nBAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMR8wHQYDVQQDDBZjb25qdXItbWFz\ndGVyLW1pbmlrdWJlMB4XDTIyMTEwMjE4NTE0OVoXDTMyMTAzMDE4NTE0OVowQzEM\nMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMMFmNvbmp1\nci1tYXN0ZXItbWluaWt1YmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB\nAQDd2/bqOsUwDLH5YfRmU0gHllUjX/LMcuseqsfdJ2XWifPEIXLhmAzcbhIR1BWq\ncncdDeC2GaWLHu9onoLdVq8iu/Pnj8wPVI42J1RR5gALAAs8iY2HxijiV0jL8laM\nibBn2hyUXNyGHlR633Z/BSW5LCw9Fqfw7i9RBRMC7qd749aZ3rnFq3Uv4mgIemjU\n9k4oLSecKBl/xo7dB9gOll1p7PXr1UECy4x+q0O9vm/lXnYNdtQmIialI/C6BWZL\nmtrhDphBgALRw8BjYbBng/sViKA2IrBGPErVlmlJzU1fz2MYmFtjqxfEOlqIWGsn\nMzAttBePP7rjlka1cV7+SH6BAgMBAAGjgagwgaUwSAYDVR0RBEEwP4IWY29uanVy\nLW1hc3Rlci1taW5pa3ViZYIWY29uanVyLW1hc3Rlci1taW5pa3ViZYINY29uanVy\nLW1hc3RlcjAdBgNVHQ4EFgQUUiThEDs33VZit3W/7nd67fGnkeowHwYDVR0jBBgw\nFoAUUiThEDs33VZit3W/7nd67fGnkeowDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMC\nAeYwDQYJKoZIhvcNAQELBQADggEBAArE1s2AbFISLfi4JzBK8u8xqyHSMk041Jgl\nWwr0Vmt2JEkgpWWuCVKrrX1B4PGc+iclPf1skyWO3IVxYaaj/5v9sdFhPq/ThvaL\nSNBlvkqAIkqfjc0Dhwoj/P2svmxPWHidCrrjQ+qzIyod+iba9KA6Ah48UI6hxPtk\nMYDC50h9bEkYXenMkM0gN8WBeiCBFN3rVpuOiO8g5mozUJ5kAj4BTJ+l/w6keWvd\nNLvXf+TBUgYE2pTSvektBW8DyWV6oFI1e6qaj1mmZoauCUy9Teg1Jb2JZUsf9Eb3\nzxadAvu7I70r5KvzsvnpILYbNpNbFOmgLBkcgLKdxTeo/faIOLE=\n-----END CERTIFICATE-----\n","CONJUR_LEADER_HOSTNAME":"conjur-master-minikube","CONJUR_LEADER_PORT":"443","CONJUR_LEADER_URL":"https://conjur-master-minikube:443","CONJUR_VERSION":"5"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"conjur-config","namespace":"cyberark"}}
  creationTimestamp: "2022-11-03T18:34:46Z"
  name: conjur-config
  namespace: user1
  resourceVersion: "2127331"
  uid: d80e1306-2f84-4fd4-b503-8431b5abe565
