#!/bin/bash

source ./gcp.config

# This script deletes running instances and brings up 
#   initialized Conjur Master, Follower & CLI nodes.
#   It also setups the Summon AWS secrets provider.

#################
main() {
  ./stop_conjur
  master_up
  cli_up
  load_demo_policy
}

#################
master_up() {
  # Bring up Conjur Master node
  $DOCKER run -d \
    --name $CONJUR_MASTER_CONTAINER_NAME \
    --label role=conjur_node \
    -p "$CONJUR_MASTER_PORT:443" \
    -p "$CONJUR_MASTER_PGSYNC_PORT:5432" \
    -p "$CONJUR_MASTER_PGAUDIT_PORT:1999" \
    --restart always \
    --security-opt seccomp:unconfined \
    $CONJUR_APPLIANCE_IMAGE 

  sleep 15	# wait till container fully started

  # Configure Conjur Master node
  echo "Configuring Conjur master..."
  $DOCKER exec $CONJUR_MASTER_CONTAINER_NAME \
                evoke configure master     \
                -h $CONJUR_MASTER_HOST_NAME \
                -p $CONJUR_ADMIN_PASSWORD \
		--master-altnames "$MASTER_ALTNAMES" \
		--follower-altnames "$FOLLOWER_ALTNAMES" \
		--accept-eula \
                $CONJUR_ACCOUNT

  mkdir -p $CACHE_DIR
  echo "Caching Conjur master cert ..."
  rm -f $CONJUR_CERT_FILE
  $DOCKER cp -L $CONJUR_MASTER_CONTAINER_NAME:/opt/conjur/etc/ssl/conjur.pem $CONJUR_CERT_FILE

  echo "Caching Conjur Follower seed files..."
  rm -f $FOLLOWER_SEED_FILE
  $DOCKER exec $CONJUR_MASTER_CONTAINER_NAME evoke seed follower conjur-follower > $FOLLOWER_SEED_FILE
}

#################
cli_up() {

  # Bring up CLI node
  # If docker-compose installed, replace "docker run..." 
  #   with "docker-compose up -d cli"
  $DOCKER run -d \
    --name $CLI_CONTAINER_NAME \
    --label role=cli \
    --restart always \
    --security-opt seccomp:unconfined \
    --entrypoint sh \
    $CLI_IMAGE_NAME \
    -c "sleep infinity"

  # if not relying on DNS - add entry for master host name to cli container's /etc/hosts
  $DOCKER exec $CLI_CONTAINER_NAME \
    bash -c "echo \"$CONJUR_MASTER_HOST_IP    $CONJUR_MASTER_HOST_NAME\" >> /etc/hosts"

  # Initialize connection to service (create .conjurrc and conjur-xx.pem cert)
  $DOCKER exec $CLI_CONTAINER_NAME \
    bash -c "echo yes | conjur init -u $CONJUR_APPLIANCE_URL -a $CONJUR_ACCOUNT"

  # Login as admin
  $DOCKER exec $CLI_CONTAINER_NAME \
    conjur authn login -u admin -p $CONJUR_ADMIN_PASSWORD
}

############################
load_demo_policy() {
  # Laod policy & init variables
  ./load_policy_REST.sh root ./policy/demo-policy.yml
  ./var_value_add_REST.sh secrets/db-username "This-is-the-DB-username"
  ./var_value_add_REST.sh secrets/db-password $(openssl rand -hex 12)
}

main "$@"
