---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: user1
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: bXlhcHBEQg==
stringData:
  conjur-map: |-
    .dockerconfigjson: DemoVault/CICD/PetClinicDev/MySQL/password
