#!/bin/bash

source ../config/conjur.config

echo "Stopping master.."
bash -c "$DOCKER stop $CONJUR_MASTER_CONTAINER_NAME >& /dev/null; $DOCKER rm $CONJUR_MASTER_CONTAINER_NAME >& /dev/null" &

echo "Stopping follower.."
bash -c "$DOCKER stop $CONJUR_FOLLOWER_CONTAINER_NAME >& /dev/null; $DOCKER rm $CONJUR_FOLLOWER_CONTAINER_NAME >& /dev/null" &

echo "Stopping cli.."
bash -c "$DOCKER stop $CLI_CONTAINER_NAME >& /dev/null; $DOCKER rm $CLI_CONTAINER_NAME >& /dev/null" &
