apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: conjur
spec:
  provider:
    conjur:
      # Service URL
      serviceUrl: https://myapi.conjur.org
      # base64 encoded string of certificate
      caBundle: "..."
      auth:
        # conjur account
        serviceAccount: myconjurserviceaccount
        secretRef:
          serviceUserRef:
            name: serviceUser
            key: conjur-user
          serviceApiKeyRef:
            name: serviceApiKey
            key: conjur-api-key
