# Service account role & binding for K8s secrets injection
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testapps

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: testapps
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: testapps
    name: testapps
roleRef:
  kind: ClusterRole
  name: secrets-access
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-access
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "patch" ]
