#!/bin/bash
source ./spring-demo.config
$DOCKER stop $MYSQL_CLIENT &> /dev/null && $DOCKER rm $MYSQL_CLIENT &> /dev/null &
echo "Stopping $MYSQL_CLIENT..."
$DOCKER stop $MYSQL_CONTAINER &> /dev/null && $DOCKER rm $MYSQL_CONTAINER &> /dev/null &
echo "Stopping $MYSQL_CONTAINER..."
