#!/bin/bash 
source spring-demo.config
echo
read -p "Remove running app container? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit -1
fi
$DOCKER stop $DEMO_CONTAINER > /dev/null \
&& $DOCKER rm $DEMO_CONTAINER > /dev/null
