---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
      annotations:
        conjur.org/debug-logging: "true"
        conjur.org/log-traces: "true"
    spec:
      serviceAccountName:  {{ .Values.conjur_app_service_account }}
      containers:
        - name: test-app
          image: alpine/curl
          imagePullPolicy: IfNotPresent
          command: ["sleep","infinity"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: conjur-status
              mountPath: /conjur/status
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

        - name: cyberark-secrets-provider-for-k8s
          image: 'cyberark/secrets-provider-for-k8s:latest'
          imagePullPolicy: IfNotPresent
          #command: ["sleep","infinity"]
          volumeMounts:
            - name: conjur-status
              mountPath: /conjur/status
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
            - name: podinfo
              mountPath: /conjur/podinfo
          env:
            - name: DEBUG
              value: "true"
            - name: CONJURAPI_LOG
              value: "stdout"
            - name: JWT_TOKEN_PATH
              value: /var/run/secrets/tokens/jwt
            - name: CONTAINER_MODE
              value: sidecar
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_SECRETS
              value: db-credentials
            - name: SECRETS_DESTINATION
              value: k8s_secrets
          envFrom:
            - configMapRef:
                name: conjur-cloud
      volumes:
        - name: conjur-status
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
