#!/bin/bash
echo "Cleaning $PWD..."
for i in $(ls -l 1-setup | grep ^d | awk '{print $9}'); do
  rm $i/manifests/*
done
for i in $(ls -l 2-use-cases | grep ^d | awk '{print $9}'); do
  rm $i/*.yaml
done
