---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # base64-encoded "test_app"
  DBName: dGVzdF9hcHAK
stringData:
  conjur-map: |-
    db-hostname: DemoVault/CICD/PetClinicDev/MySQL/address
    db-name: DemoVault/CICD/PetClinicDev/MySQL/database
    username: DemoVault/CICD/PetClinicDev/MySQL/username
    password: DemoVault/CICD/PetClinicDev/MySQL/password
