---
apiVersion: batch/v1
kind: Job
metadata:
  name: secrets-provider
spec:
  template:
    spec:

      restartPolicy: OnFailure

      containers:
      - image: cyberark/secrets-provider-for-k8s:latest
        imagePullPolicy: IfNotPresent

        name: secrets-provider
        env:
          - name: CONTAINER_MODE
            value: application

          - name: CONJUR_AUTHN_URL
            value: https://conjur-follower.cyberark.svc.cluster.local/api/authn-k8s/mac-k8s

          - name: CONJUR_AUTHN_LOGIN
            value: host/user1/app-example-k8ssecrets

          - name: SECRETS_DESTINATION
            value: k8s_secrets

          - name: K8S_SECRETS
            value: db-credentials

          - name: DEBUG
            value: "true"

        # values from pod metadata
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

        # values from Conjur config map
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: conjur-config
                key: CONJUR_VERSION
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: conjur-config
                key: CONJUR_APPLIANCE_URL
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: conjur-config
                key: CONJUR_ACCOUNT
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: conjur-config
                key: CONJUR_FOLLOWER_CERTIFICATE
