# Grants the default service account a rolebinding
# to a role for secrets access & patching.
# Apps run as the default service account unless
# otherwise specified. Similarly, the application 
# identity in DAP assumes the default SA unless 
# otherwise specified.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user1-secrets-access-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: user1 
  name: user1-secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: user1
    name: default
roleRef:
  kind: Role
  name: user1-secrets-access-role
  apiGroup: rbac.authorization.k8s.io
