---
# Define project namespace
apiVersion: v1
kind: Namespace
metadata:
  name: user1
  labels:
    name: user1

---
# Grant the authentication service access to pods in user1 namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-follower-access-grant
  namespace: user1
subjects:
- kind: ServiceAccount
  name: conjur-follower
  namespace: cyberark
roleRef:
  kind: ClusterRole
  name: conjur-authn-role
  apiGroup: rbac.authorization.k8s.io

---
# Grant user1 namespace admin privileges
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
  namespace: user1
subjects:
- kind: User
  name: user1
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
