---
- name: CyberArk Demo
  hosts:
  - localhost
  - ConjurMaster2.northcentralus.cloudapp.azure.com
  gather_facts: false
  tasks:
    - debug: msg="Access Key ID - {{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    - debug: msg="Secret Access Key - {{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    - name: Login directory listing
      ansible.builtin.shell: ls
      register: command_output
    - debug:
        var: command_output.stdout_lines
